export const planTypes = [
  {
    id: 'daily',
    name: 'Daily Production Plan',
    icon: 'Calendar',
    category: 'Daily',
    description: 'Create a production plan for a single day.',
    useCases: ['Daily Target', 'Daily Production', 'Daily Manpower', 'Daily Shift Planning'],
    estimatedTime: '2-3 minutes',
    benefits: [
      "Fastest way to lock a single day's targets",
      'Auto-pulls machine and operator availability',
      'Ideal for quick shift-level adjustments',
    ],
    requiredInfo: ['Production date', 'Shift', 'Machine allocation', 'Target output'],
    recommendedFor: 'Shift supervisors planning day-to-day floor operations.',
  },
  {
    id: 'weekly',
    name: 'Weekly Production Plan',
    icon: 'CalendarDays',
    category: 'Weekly',
    description: 'Create a production schedule for one week.',
    useCases: ['Weekly Targets', 'Shift Planning', 'Material Planning', 'Capacity Planning'],
    estimatedTime: '4-5 minutes',
    benefits: [
      'Balances load across shifts for the full week',
      'Flags material shortages before they happen',
      'Keeps capacity in sync with weekly demand',
    ],
    requiredInfo: ['Week start date', 'Shift pattern', 'Material availability', 'Capacity targets'],
    recommendedFor: 'Production planners coordinating multi-shift, multi-line output.',
  },
  {
    id: 'monthly',
    name: 'Monthly Production Plan',
    icon: 'CalendarRange',
    category: 'Monthly',
    description: 'Plan complete monthly production.',
    useCases: ['Production Forecast', 'Machine Utilization', 'Capacity Management', 'Monthly Target'],
    estimatedTime: '5-7 minutes',
    benefits: [
      'Forecasts output against monthly commitments',
      'Surfaces machine utilization gaps early',
      'Aligns capacity with sales and dispatch targets',
    ],
    requiredInfo: ['Month', 'Machine-wise forecast', 'Utilization targets', 'Monthly target volume'],
    recommendedFor: 'Plant managers setting monthly targets across all halls.',
  },
  {
    id: 'custom',
    name: 'Custom Plan',
    icon: 'Settings2',
    category: 'Custom',
    description: 'Create a customized production plan with flexible dates.',
    useCases: ['Trial Production', 'Special Orders', 'Customer Orders', 'New Product Launch'],
    estimatedTime: '5 minutes',
    benefits: [
      'Works for any date range, not tied to a calendar cycle',
      'Built for one-off runs and special requirements',
      'Flexible enough for new product trials',
    ],
    requiredInfo: ['Start & end date', 'Order / customer reference', 'Special requirements'],
    recommendedFor: 'Teams handling trial runs, special orders, or new launches.',
  },
];